### PR TITLE
Correct type of contact attribute and 3 other issues

### PR DESCRIPTION
**Pull request by anuragkapur**
Addresses https://github.com/interfax/interfax-java/issues/29

### CODE REVIEW

**Comment by anuragkapur** [comment]
@cbetta - ok if I merge this? Have tested this on my local machine, via an integration test.

**Comment by anuragkapur** [comment]
Also addresses - https://github.com/interfax/interfax-java/issues/27, https://github.com/interfax/interfax-java/issues/26, https://github.com/interfax/interfax-java/issues/22

**Comment by cbetta** [comment]
Tnx for the quick fix @anuragkapur. Can you do me a favor and ensure that this shipped correctly to the package manager?

**Comment by anuragkapur** [comment]
Yup, sure. I am monitoring the travis job and will verify that a new release artifact is available on maven central.

**Comment by anuragkapur** [comment]
v0.12 now available on maven central (package manager).

**Pull request merged**
